import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";

import { ThemeProvider } from "@/src/theme/theme-provider"
import LoginModal from "./components/modals/LoginModal";
import SignupModal from "./components/modals/SignupModal";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DjangoBnB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const content = (
      <p>Yo yo!</p>
    )
 

  return (
    
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar />
        
        <div className="pt-32">
          {children}
        </div>

        <LoginModal />
        <SignupModal />

        </ThemeProvider>
      </body>
    </html>
  );
}
